// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecialResource) DeepCopyInto(out *SpecialResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecialResource.
func (in *SpecialResource) DeepCopy() *SpecialResource {
	if in == nil {
		return nil
	}
	out := new(SpecialResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpecialResource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecialResourceDependency) DeepCopyInto(out *SpecialResourceDependency) {
	*out = *in
	in.HelmChart.DeepCopyInto(&out.HelmChart)
	in.Set.DeepCopyInto(&out.Set)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecialResourceDependency.
func (in *SpecialResourceDependency) DeepCopy() *SpecialResourceDependency {
	if in == nil {
		return nil
	}
	out := new(SpecialResourceDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecialResourceList) DeepCopyInto(out *SpecialResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpecialResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecialResourceList.
func (in *SpecialResourceList) DeepCopy() *SpecialResourceList {
	if in == nil {
		return nil
	}
	out := new(SpecialResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpecialResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecialResourceSpec) DeepCopyInto(out *SpecialResourceSpec) {
	*out = *in
	in.Chart.DeepCopyInto(&out.Chart)
	in.Set.DeepCopyInto(&out.Set)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]SpecialResourceDependency, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecialResourceSpec.
func (in *SpecialResourceSpec) DeepCopy() *SpecialResourceSpec {
	if in == nil {
		return nil
	}
	out := new(SpecialResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpecialResourceStatus) DeepCopyInto(out *SpecialResourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpecialResourceStatus.
func (in *SpecialResourceStatus) DeepCopy() *SpecialResourceStatus {
	if in == nil {
		return nil
	}
	out := new(SpecialResourceStatus)
	in.DeepCopyInto(out)
	return out
}
