{{- $appName := printf "%s-driver-container" .Release.Name }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: {{ $appName }}
  name: {{ $appName }}
  annotations:
    specialresource.openshift.io/wait: "true"
    specialresource.openshift.io/state: "driver-container"
    specialresource.openshift.io/driver-container-vendor: sro-ci
    specialresource.openshift.io/kernel-affine: "true"
spec:
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
    spec:
      containers:
        - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          name: modprobe
          command: [sleep, infinity]
          lifecycle:
            postStart:
              exec:
                command: [modprobe, -v, sro_ci]
            preStop:
              exec:
                command: [modprobe, -vr, sro_ci]
          securityContext:
            capabilities:
              add: [SYS_MODULE]
